### PR TITLE
some more examples SymPy PI

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Could you add the new formulas to formulas.html also?

**Comment by gxyd** [comment]
I have added the formulas. Though i am not good at writing `LaTex` code.

**Comment by fredrik-johansson** [comment]
Thanks. Don't worry, I can adjust it.

**Comment by gxyd** [comment]
Can i add the `LaTex` for the remaining examples? (If you aren't working on them?)

**Comment by fredrik-johansson** [comment]
I'm not working on it. You're welcome to do so.

**Pull request merged**
